SELECT 
null AS "Id", 
null AS "IsDeleted", 
null AS "AccountId", 
null AS "Name", 
"Lead"."Description" As "Description", 
CASE
END AS StageName, 
null AS "Amount", 
null AS "Probability", 
null AS "CloseDate", 
null AS "NextStep", 
null AS "IsClosed", 
null AS "IsWon", 
null AS "CampaignId", 
null AS "HasOpportunityLineItem", 
null AS "Pricebook2Id", 
null AS "OwnerId", 
null AS "CreatedDate", 
null AS "CreatedById", 
null AS "LastModifiedDate", 
null AS "LastModifiedById", 
null AS "SystemModstamp", 
null AS "LastActivityDate", 
null AS "PushCount", 
null AS "LastStageChangeDate", 
null AS "FiscalQuarter", 
null AS "FiscalYear", 
null AS "Fiscal", 
null AS "ContactId", 
null AS "LastViewedDate", 
null AS "LastReferencedDate", 
null AS "HasOpenActivity", 
null AS "HasOverdueTask", 
null AS "LastAmountChangedHistoryId", 
null AS "LastCloseDateChangedHistoryId"
FROM Lead