SELECT 
"test"."furst bane" As "Id", 
null AS "IsDeleted", 
null AS "MasterRecordId", 
null AS "Name", 
CASE
WHEN "test"."furst bane" = 'lsda' THEN 'Analyst'
WHEN "test"."furst bane" = 'afs' THEN 'Prospect'
WHEN "test"."furst bane" = 'da' THEN 'Press'
WHEN "test"."furst bane" = 'fdas' THEN 'Reseller'
WHEN "test"."furst bane" = 'fa' THEN 'Press'
END AS Type, 
null AS "ParentId", 
null AS "BillingStreet", 
null AS "BillingCity", 
null AS "BillingState", 
null AS "BillingPostalCode", 
null AS "BillingCountry", 
null AS "BillingLatitude", 
null AS "BillingLongitude", 
null AS "BillingAddress", 
null AS "ShippingStreet", 
null AS "ShippingCity", 
null AS "ShippingState", 
null AS "ShippingPostalCode", 
null AS "ShippingCountry", 
null AS "ShippingLatitude", 
null AS "ShippingLongitude", 
null AS "ShippingAddress", 
null AS "Phone", 
null AS "Fax", 
null AS "Website", 
null AS "PhotoUrl", 
null AS "AnnualRevenue", 
null AS "NumberOfEmployees", 
null AS "Description", 
null AS "OwnerId", 
null AS "CreatedDate", 
null AS "CreatedById", 
null AS "LastModifiedDate", 
null AS "LastModifiedById", 
null AS "SystemModstamp", 
null AS "LastActivityDate", 
null AS "LastViewedDate", 
null AS "LastReferencedDate", 
null AS "Jigsaw", 
null AS "JigsawCompanyId", 
null AS "SicDesc", 
null AS "SFSSDupeCatcher__Override_DupeCatcher__c", 
"test"."furst bane" As "IsPriorityRecord", 
null AS "Billing_Email__c", 
null AS "QB_Id__c", 
null AS "Legacy_Id__c", 
null AS "test_in_julyw__c", 
null AS "Converted_From_Lead__c", 
null AS "Developer_Type__c", 
null AS "cron_test__c", 
null AS "SIC_2_digit__c"
FROM test